Update landing page docs.
vercel/edge-runtime pull request #29
Opened 2022-07-17 16:25 UTC by leerob

2022-07-17 16:49 UTC, balazsorban44 requested changes

2022-07-17 16:49 UTC, balazsorban44 commented on docs/pages/index.mdx
> +When developing and testing locally, the Edge RUntime will polyfill Web APIs and ensure compatibility with the Node.js layer.
```suggestion
When developing and testing locally, the Edge Runtime will polyfill Web APIs and ensure compatibility with the Node.js layer.
```

2022-07-18 00:53 UTC, leerob commented on docs/pages/index.mdx
> +When your framework is built on the Edge Runtime, it runs everywhere Node.js does. When deployed to infrastructure like Vercel, frameworks like Next.js can automatically provision the optimal infrast
```suggestion
When your framework is built on the Edge Runtime, it runs everywhere Node.js does. When deployed to infrastructure like Vercel, frameworks like Next.js can automatically provision the optimal infrastructure for you.
```

2022-07-18 00:54 UTC, leerob commented on docs/pages/index.mdx
> +The Edge Runtime is a subset of standard Web APIs, giving you compatability and interoperability with the highest number of environments. This project is developed as part of [WinterCG](https://winte
```suggestion
The Edge Runtime is a subset of standard Web APIs, giving you compatibility and interoperability with the highest number of environments. This project is developed as part of [WinterCG](https://wintercg.org) – a community group between Vercel, Cloudflare, Deno, Shopify, and more. The term “Edge” refers to the orientation toward instant serverless compute environments and not a specific set of locations.
```

2022-07-18 07:39 UTC, Kikobeats commented
😍

2022-07-18 07:39 UTC, merged